### ISSUE TITLE
Exception: finish pending transaction which is no longer in config

### ISSUE THREAD

**Issue by keesvandieren** [libgdx/gdx-pay#113]
On startup, gdx-pay tries to finish pending transactions.

If this happens to be for a product that is no longer in the PurchaseManagerConfig.

Exception that occurs will be:

java.lang.NullPointerException
        at com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple.transaction(PurchaseManageriOSApple.java:222)
        at com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple$AppleTransactionObserver.updatedTransactions(PurchaseManageriOSApple.java:451)
        at com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple$AppleProductsDelegate.didReceiveResponse(PurchaseManageriOSApple.java:322)
        at com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple$AppleProductsDelegate.$cb$productsRequest$didReceiveResponse$(PurchaseManageriOSApple.java)
        at org.robovm.apple.uikit.UIApplication.main(Native Method)
        at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:413)

**Comment by keesvandieren** [comment]
Fixed in 0.10.1
