### ISSUE TITLE
GdxPayException: onServiceDisconnected() received - on Android after pause/resume

### ISSUE THREAD

**Issue by codeulike** [libgdx/gdx-pay#138]
Using GdxPay on Android, along the lines of the 'Integration example with resolvers' on the wiki.

Starts up fine, purchases work etc. 

Sometimes (and only sometimes) after switching back and forth between my app and something else I get this error. It happens when switching back to my app, so presumably onResume:

```
com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.pay.android.googleplay.GdxPayException: Failed to bind to service
	at com.mynamespace.mygame$1.handleInstallError(NumPlusGame.java:387)
	at com.badlogic.gdx.pay.android.googleplay.AndroidGooglePlayPurchaseManager$1.disconnected(AndroidGooglePlayPurchaseManager.java:117)
	at com.badlogic.gdx.pay.android.googleplay.billing.V3GoogleInAppBillingService$BillingServiceInitializingServiceConnection.onServiceDisconnected(V3GoogleInAppBillingService.java:387)
	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1469)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1483)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: com.badlogic.gdx.pay.android.googleplay.GdxPayException: Failed to bind to service
	... 11 more
Caused by: com.badlogic.gdx.pay.android.googleplay.GdxPayException: onServiceDisconnected() received.
	... 10 more
```

Not sure why this is happening, it only happens sometimes. Should I be doing anything specific with GdxPay when pause/resume is called?

**Comment by codeulike** [comment]
I'm now catching that specific error in  handleInstallError() (by drilling down into getCause() and checking strings) and ignoring it, everything still seems to work fine. I think its something that happens when Android is destroying the Activity, maybe.

**Comment by codeulike** [comment]
Had a question about this, so here is the code I used in handleInstallError() in the end. As far as I can tell, the error "Failed to bind to service" can be ignored on Android, I think it happens during destroy of the app. Other exceptions that end up in handleInstallError() _do_ need to be handled, e.g. by disabling the shop functionality in your app.

```
@Override
public void handleInstallError (Throwable e) {


          // check for disconnect error on android
          if (e.getMessage().startsWith("Failed to bind to service"))
          {
              if (e.getCause() != null && e.getCause().getMessage().startsWith("onServiceDisconnected() received"))
              {
                  // ignore for now
                  Gdx.app.log("HandleInstallError", "onServiceDisconnected() received");

                  return;
              }
          }
          Gdx.app.log("ERROR", "PurchaseObserver: handleInstallError!: " + e.getMessage());
          Gdx.app.error("ERROR", "PurchaseObserver: handleInstallError!: " + e.getMessage(), e);
          // continue with shop in disabled mode

          startShopDisabled(e.getMessage());


}
```
