### ISSUE TITLE
Failed to invoke onActivityResult(...) on purchase manager. When making a purchase

### ISSUE THREAD

**Issue by MrCharli3** [libgdx/gdx-pay#146]
I am trying to purchase the static test product 'android.test.purchased'. But When I do it gives me the following error after I have pressed "buy" and Google tells me the purchase was successful (This is after handlePurchase and checkTransaction has been called):

`05-19 16:42:10.584 5224-5224/com.nielstrom.spacepack.android D/GdxPay/IAP: Failed to invoke onActivityResult(...) on purchase manager.
                                                                           java.lang.NoSuchMethodException: onActivityResult [int, int, class android.content.Intent]
                                                                               at java.lang.Class.getMethod(Class.java:1981)
                                                                               at java.lang.Class.getMethod(Class.java:1637)
                                                                               at com.badlogic.gdx.pay.android.IAP.onActivityResult(IAP.java:167)
                                                                               at com.badlogic.gdx.backends.android.AndroidApplication.onActivityResult(AndroidApplication.java:481)
                                                                               at com.nielstrom.spacepack.android.AndroidLauncher.onActivityResult(AndroidLauncher.java:155)
                                                                               at android.app.Activity.dispatchActivityResult(Activity.java:7226)
                                                                               at android.app.ActivityThread.deliverResults(ActivityThread.java:4521)
                                                                               at android.app.ActivityThread.handleSendResult(ActivityThread.java:4568)
                                                                               at android.app.ActivityThread.-wrap22(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1706)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

I have followed the wiki when implementing, what could be causing this?

OnActivityResult method:
`@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data)
    {
        super.onActivityResult(requestCode, resultCode, data);
    }`

Even when I run the official example: https://bitbucket.org/just4phil/gdxpayexample, I get the same result

Note: The app doesnt crash from this error, but if I try to put code in "checkTransaction", i.e the full logic for my "full version", it crashes".

**Comment by Berobasket** [comment]
Did you find any reason for this?
