### ISSUE TITLE
Error creating IAP for Android, java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by portfort** [libgdx/gdx-pay#165]
I'm getting the following error when I run my game. I think it started when I upgraded from Android Studio 2.2.? to 3.0.1
It was working fine on Android Studio 2.
I'm using gdxPayVersion 0.11.2 and gdxVersion 1.9.7 and roboVMVersion 2.3.3
I'm not sure if this is even a gdx-pay problem or a libgdx problem

03-14 14:29:26.434 16865-16865/com.zuzzgb.aircombateer.android I/GdxPay/IAP: IAP: Error creating IAP for Android.
	java.lang.NoSuchMethodException: addAndroidEventListener [interface com.badlogic.gdx.backends.android.g]
		at java.lang.Class.getMethod(Class.java:1981)
		at java.lang.Class.getMethod(Class.java:1637)
		at com.badlogic.gdx.pay.android.IAP.setup(SourceFile:99)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.badlogic.gdx.utils.b.e.a(SourceFile:108)
		at com.badlogic.gdx.pay.h.e(SourceFile:70)
		at com.badlogic.gdx.pay.h.a(SourceFile:90)
		at com.badlogic.gdx.pay.h.b(SourceFile:99)
		at com.zuzzgb.aircombateer.z.a(SourceFile:26)
		at com.zuzzgb.aircombateer.android.a.<init>(SourceFile:19)
		at com.zuzzgb.aircombateer.android.AndroidLauncher.onCreate(SourceFile:145)
		at android.app.Activity.performCreate(Activity.java:6910)
		at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
		at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
		at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
		at android.app.ActivityThread.-wrap12(ActivityThread.java)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
		at android.os.Handler.dispatchMessage(Handler.java:105)
		at android.os.Looper.loop(Looper.java:156)
		at android.app.ActivityThread.main(ActivityThread.java:6523)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by Tom-Ski** [comment]
Disable proguard and see if you still have the same problem.

**Comment by portfort** [comment]
Yup, that's the problem. Do you know what I should put in proguard rules to fix this?

**Comment by Tom-Ski** [comment]
https://github.com/libgdx/gdx-pay/wiki/Proguard

**Comment by Tom-Ski** [comment]
`addAndroidEventListener` not being found means that its being stripped or renamed. So if the above rules don't work, you may want to debug what you need to do. Either adding exception for rename for that method and class, or prevent it being stripped if it is being stripped.

**Comment by portfort** [comment]
The link you provided fixed it. Thanks!
