### ISSUE TITLE
NPE on start of the app (getTransactionDate() or getTransactionDate().toDate() is null)

### ISSUE THREAD

**Issue by prineside** [libgdx/gdx-pay#240]
#### Issue details, reproduction steps/code
_App crashes due to the uncaught NullPointerException at the start, probably only if user has made a purchase before_

#### Version of gdx-pay and/or relevant dependencies
_gdx-pay 1.3.2_

#### Stacktrace
```java
java.lang.NullPointerException
	at com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple.transaction(PurchaseManageriOSApple.java:211)
	at com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple$AppleTransactionObserver.updatedTransactions(PurchaseManageriOSApple.java:368)
	at com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple$AppleTransactionObserver.$cb$paymentQueue$updatedTransactions$(PurchaseManageriOSApple.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:446)
```

#### Please select the affected platforms and payment service implementation
- [ ] Amazon
- [ ] googlebilling
- [ ] googlepay
- [x] apple robovm
- [ ] Huawei

**Comment by MrStahlfelge** [comment]
https://github.com/libgdx/gdx-pay/blob/374be35fd8df357f145ab7d283a35897abd2424f/gdx-pay-iosrobovm-apple/src/main/java/com/badlogic/gdx/pay/ios/apple/PurchaseManageriOSApple.java#L211

Must be getTransactionDate() that returns null. But the line is seven years old, I wonder why we didn't encounter problems before.

**Comment by prineside** [comment]
Maybe one of the iOS updates has changed something. I've received more than a dozen of reports from different users referring to this exception

If transaction date is not critical for the library, checking for null and using current time as a fallback should be sufficient

**Comment by MrStahlfelge** [comment]
That should be a good solution. Can you provide a PR?
