### ISSUE TITLE
crash logs seen from Firebase after upgrading the gdx-pay from 1.3.1 to 1.3.4

### ISSUE THREAD

**Issue by bitdream** [libgdx/gdx-pay#253]
Please ensure you have given all the following requested information in your report.

#### Issue details, reproduction steps/code
_Please provide the details of your issue_
I saw crash logs from Firebase after upgrading the gdx-pay from 1.3.1 to 1.3.4.

#### Version of gdx-pay and/or relevant dependencies
_Please provide the version(s) affected._
1.3.4
#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx/com.android.billingclient.api.ProxyBillingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.IntentSender android.app.PendingIntent.getIntentSender()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.IntentSender android.app.PendingIntent.getIntentSender()' on a null object reference
       at com.android.billingclient.api.ProxyBillingActivity.onCreate(SourceFile:12)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

#### Please select the affected platforms and payment service implementation
- [ ] Amazon
- [ ] googlebilling
- [x] googlepay
- [ ] apple robovm
- [ ] Huawei

**Comment by keesvandieren** [comment]
How often does it happen?

Are you able to reproduce it?

Is it happening on specific Android versions, specific device models?

**Comment by keesvandieren** [comment]
Are they of different users?

**Comment by bitdream** [comment]
From the firebase info they are different users. 
However, I'm a bit doubt about it because they are of the exact phone type and OS version.

**Comment by bitdream** [comment]
It hasn't been seen for some while. Maybe a very rare case..
