### ISSUE TITLE
SecurityException with gdx-pay on Android

### ISSUE THREAD

**Issue by klianc09** [libgdx/gdx-pay#256]
#### Issue details, reproduction steps/code
My game crashes on an user's phone with a SecurityException.

#### Version of gdx-pay and/or relevant dependencies

using version 1.3.4
"com.badlogicgames.gdxpay:gdx-pay-android-googlebilling:1.3.4"

#### Stacktrace
```java
java.lang.SecurityException: Not allowed to bind to service Intent { act=com.android.vending.billing.InAppBillingService.BIND pkg=com.android.vending cmp=com.android.vending/com.google.android.finsky.billing.iab.InAppBillingService (has extras) }
at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2064)
at android.app.ContextImpl.bindService(ContextImpl.java:1976)
at android.content.ContextWrapper.bindService(ContextWrapper.java:829)
at com.android.billingclient.api.BillingClientImpl.startConnection(com.android.billingclient:billing@@5.0.0:52)
at com.badlogic.gdx.pay.android.googlebilling.PurchaseManagerGoogleBilling.startServiceConnection(PurchaseManagerGoogleBilling.java:78)
at com.badlogic.gdx.pay.android.googlebilling.PurchaseManagerGoogleBilling.install(PurchaseManagerGoogleBilling.java:61)
[...]
```

#### Please select the affected platforms and payment service implementation
- [ ] Amazon
- [x] googlebilling
- [ ] googlepay
- [ ] apple robovm
- [ ] Huawei

**Comment by keesvandieren** [comment]
@klianc09 can you let us know whether this error is still there? Is it working for most users?

**Comment by klianc09** [comment]
Looked through the crashlogs in the last 60 days it has only occurred once and that was for
`samsung a11q (Galaxy A11) (running Android 12 (SDK 31))`
So it seems to be working for most users.

It's still *there* but it isn't a priority. Was unable to reproduce it. I was trying to understand what was going on but it hardly seems worth the effort.

**Comment by keesvandieren** [comment]
Please reopen when able to reproduce
