### ISSUE TITLE
iOS development build crashes

### ISSUE THREAD

**Issue by SakiiCode** [libgdx/gdx-pay#268]
#### Issue details, reproduction steps/code
Installing production build over testflight works fine, but when installing development build over usb the application crashes at startup

#### Version of gdx-pay and/or relevant dependencies
1.3.7

#### Stacktrace
```
java.lang.NoClassDefFoundError: com/badlogic/gdx/pay/ios/apple/PurchaseManageriOSApple
     at **********.IOSLauncher.createApplication(IOSLauncher.java:16)
     at com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.didFinishLaunching(IOSApplication.java:62)
     at com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.$cb$application$didFinishLaunchingWithOptions$(IOSApplication.java)
     at org.robovm.apple.uikit.UIApplication.main(Native Method)
     at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:433)
     at **********.IOSLauncher.main(IOSLauncher.java:22)
```

#### Please select the affected platforms and payment service implementation
- [ ] Amazon
- [ ] googlebilling
- [ ] googlepay
- [x] apple robovm
- [ ] Huawei

**Comment by keesvandieren** [comment]
Have you followed the instructions in readme?

Best regards / Hartelijke groeten,

Kees van Dieren
Eigenaar

Squins IT Solutions BV
Oranjestraat 30
2983 HS Ridderkerk
The Netherlands
Mobile: +31 (0)6 30413841
www.squins.com
Chamber of commerce Rotterdam: 24435103



Plan een afspraak in <https://calendar.app.google/oz1RkqibKgRsMQUdA>


Op za 28 dec 2024 om 11:19 schreef Sakii ***@***.***>

**Comment by SakiiCode** [comment]
Yes

Since then I discovered that replacing "implementation" with "api" fixes the crash.
I can even use the sandbox accounts function now
