### ISSUE TITLE
NPE in PurchaseManagerAndroidOpenIAB setup callback

### ISSUE THREAD

**Issue by alex-dorokhov** [libgdx/gdx-pay#45]
Using latest gdx-pay and google play store I got the following exception:

```java
java.lang.NullPointerException
       at com.badlogic.gdx.pay.android.openiab.PurchaseManagerAndroidOpenIAB$1$1.onIabSetupFinished(PurchaseManagerAndroidOpenIAB.java:248)
       at org.onepf.oms.appstore.googleUtils.IabHelper$1.onServiceConnected(IabHelper.java:267)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1110)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1127)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5050)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Seems, **helper** was set to null before OpenIAB had replied...

**Comment by noblemaster** [comment]
Merged!
